import type { Metadata } from "next";
import { Tajawal } from "next/font/google";
import "./globals.css";
import { NextIntlClientProvider } from "next-intl";
import { getMessages, setRequestLocale } from "next-intl/server";
import { notFound } from "next/navigation";
import { routing } from "@/i18n/routing";
import { Directions, LANGUAGES } from "@/constants/enum";
import { ThemeProvider } from "@/providers/theme-provider";
import Header from "@/app/[locale]/_component/header";
import Sidebar from "@/app/[locale]/_component/sidebar";
import { SidebarProvider } from "@/context/sidebar";
import { headers } from "next/headers";
import PageTitle from "./_component/PageTitle";
import SearchForm from "./_component/header/navbar/search-form";

const tajawal = Tajawal({
  subsets: ["latin", "arabic"],
  weight: ["200", "400", "500", "700"],
  variable: "--font-tajawal",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export function generateStaticParams() {
  return routing.locales.map((locale) => ({ locale }));
}

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}>) {
  const { locale } = await params;
  const headersList = headers();
  // read the custom x-url header
  const header_url = (await headersList).get("x-url") || "";
  console.log(header_url);
  const messages = await getMessages();
  // Ensure that the incoming `locale` is valid
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  if (!routing.locales.includes(locale as any)) {
    notFound();
  }

  // Enable static rendering
  setRequestLocale(locale);

  const isArabic = locale === LANGUAGES.ARABIC;
  return (
    <html
      lang={locale}
      dir={isArabic ? Directions.RTL : Directions.LTR}
      suppressHydrationWarning
    >
      <body className={`${tajawal.variable}`}>
        <NextIntlClientProvider messages={messages}>
          <ThemeProvider
            attribute="class"
            defaultTheme="light"
            disableTransitionOnChange
          >
            <SidebarProvider>
              <div className="w-full min-h-14">
                <Header />
              </div>
              <Sidebar />
              <main className="dark md:ms-64">
                <SearchForm className="md:hidden" />
                <PageTitle />
                {children}
              </main>
            </SidebarProvider>
          </ThemeProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
